package com.ftu.admin.consumer.entity;

// default package
// Generated Aug 12, 2015 2:25:08 PM by Hibernate Tools 3.4.0.CR1

/**
 * SecIpDetail generated by hbm2java
 */
public class IPAddressEntity implements java.io.Serializable {

	private String ipAddress;
	private String ipGroupCode;

	public IPAddressEntity() {
	}

	public String getIpAddress() {
		return ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	public String getIpGroupCode() {
		return ipGroupCode;
	}

	public void setIpGroupCode(String ipGroupCode) {
		this.ipGroupCode = ipGroupCode;
	}

}
