package com.ftu.admin.consumer.entity;
// default package
// Generated Aug 12, 2015 2:25:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * SecRole generated by hbm2java
 */
@XmlRootElement
public class RoleEntity implements java.io.Serializable {

	private int roleId;
	private String code;
	private String name;
	private String status;
	//private Set secIdentityRoles = new HashSet(0);

	public RoleEntity() {
	}

	public RoleEntity(int roleId, String code, String name, String status) {
		this.roleId = roleId;
		this.code = code;
		this.name = name;
		this.status = status;
	}

	public RoleEntity(int roleId, String code, String name, String status,
			Set secIdentityRoles) {
		this.roleId = roleId;
		this.code = code;
		this.name = name;
		this.status = status;
		//this.secIdentityRoles = secIdentityRoles;
	}

	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

//	public Set getSecIdentityRoles() {
//		return this.secIdentityRoles;
//	}
//
//	public void setSecIdentityRoles(Set secIdentityRoles) {
//		this.secIdentityRoles = secIdentityRoles;
//	}

}
