
package com.ftu.convertservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Converter", targetNamespace = "http://service.convert.viettel.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Converter {


    /**
     * 
     * @param input
     * @return
     *     returns com.ftu.convertservice.PdfDocxFile
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "convert", targetNamespace = "http://service.convert.viettel.com/", className = "com.ftu.convertservice.Convert")
    @ResponseWrapper(localName = "convertResponse", targetNamespace = "http://service.convert.viettel.com/", className = "com.ftu.convertservice.ConvertResponse")
    @Action(input = "http://service.convert.viettel.com/Converter/convertRequest", output = "http://service.convert.viettel.com/Converter/convertResponse")
    public PdfDocxFile convert(
        @WebParam(name = "input", targetNamespace = "")
        PdfDocxFile input);

}
